### ISSUE TITLE
Memory leak when AppsStudio bin directory is present

### ISSUE THREAD

**Issue by fsahmad** [gfrancischini/appsbuilder#37]
Tried to build the apps project, but failed several times because there was a apps studio bin folder present. 

After that, I noticed the following processes:

![image](https://cloud.githubusercontent.com/assets/11634036/21191404/fdaecfaa-c1f2-11e6-8af7-c611f4f9e8fb.png)

Found in Apps Builder Extension 0.1.3

**Comment by gfrancischini** [comment]
Currently we delete the folder AppsStudio bin before continue the build
